# Generated by Django 5.0.6 on 2025-10-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twilio_sid', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('from_number', models.CharField(db_index=True, max_length=32)),
                ('to_number', models.CharField(max_length=32)),
                ('status', models.CharField(default='initiated', max_length=32)),
                ('transcript', models.TextField(blank=True, null=True)),
                ('stage', models.CharField(default='start', max_length=32)),
                ('slots_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
